---

- hosts: localhost
  #connection: ssh

  tasks:
    - name: Installing dependency java
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: getting jenkins file from jenkins.io
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: importing the jenkins keys from jenkins.io
      ansible.builtin.rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: installing jenkins
      yum:
        name: jenkins
        state: present

    - name: starting jenkins
      service:
        name: jenkins
        state: started

